#ifndef __YAW_FUSION_CFG_H__
#define __YAW_FUSION_CFG_H__

#define YAW_FUSION_CFG_DEFAULT_ENC_COUNTS_PER_REV      8192u
#define YAW_FUSION_CFG_DEFAULT_ENC_DIR                 1
#define YAW_FUSION_CFG_DEFAULT_GYRO_DIR                1
#define YAW_FUSION_CFG_DEFAULT_K_ENC                   0.02f
#define YAW_FUSION_CFG_DEFAULT_BIAS_ALPHA_STATIC       0.002f
#define YAW_FUSION_CFG_DEFAULT_TEMP_REF_C              25.0f
#define YAW_FUSION_CFG_DEFAULT_K_TEMP_RAD_S_PER_C      0.0f
#define YAW_FUSION_CFG_DEFAULT_STATIC_GYRO_TH_RAD_S    0.03f
#define YAW_FUSION_CFG_DEFAULT_STATIC_ENC_VEL_TH_RAD_S 0.02f
#define YAW_FUSION_CFG_DEFAULT_STATIC_ACC_NORM_TH_G    0.05f
#define YAW_FUSION_CFG_DEFAULT_STATIC_CONFIRM_SAMPLES  100u
#define YAW_FUSION_CFG_DEFAULT_DT_MIN_S                0.0002f
#define YAW_FUSION_CFG_DEFAULT_DT_MAX_S                0.0100f

#define YAW_FUSION_CFG_DEFAULT_INITIALIZER \
{ \
    YAW_FUSION_CFG_DEFAULT_ENC_COUNTS_PER_REV, \
    YAW_FUSION_CFG_DEFAULT_ENC_DIR, \
    YAW_FUSION_CFG_DEFAULT_GYRO_DIR, \
    YAW_FUSION_CFG_DEFAULT_K_ENC, \
    YAW_FUSION_CFG_DEFAULT_BIAS_ALPHA_STATIC, \
    YAW_FUSION_CFG_DEFAULT_TEMP_REF_C, \
    YAW_FUSION_CFG_DEFAULT_K_TEMP_RAD_S_PER_C, \
    YAW_FUSION_CFG_DEFAULT_STATIC_GYRO_TH_RAD_S, \
    YAW_FUSION_CFG_DEFAULT_STATIC_ENC_VEL_TH_RAD_S, \
    YAW_FUSION_CFG_DEFAULT_STATIC_ACC_NORM_TH_G, \
    YAW_FUSION_CFG_DEFAULT_STATIC_CONFIRM_SAMPLES, \
    YAW_FUSION_CFG_DEFAULT_DT_MIN_S, \
    YAW_FUSION_CFG_DEFAULT_DT_MAX_S \
}

#endif /* __YAW_FUSION_CFG_H__ */
